### ISSUE TITLE
[Enhancement] Allow passing values from one task to another task

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/automation-app#32]
[Enhancement] Allow passing values from one task to another task
Or something similar to the GitHub Actions `outputs` or `env_var`.

```
tasks:
  - call: get-date@default
     id: task1
  - call: print-to-console@default
     args:
       text: ${{ task1.outputs.textString }}
```

Thanks.
