### ISSUE TITLE
Adding a Dockerfile to run the app through docker

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/automation-app#9]
Adding a Dockerfile to run the app through docker

**Comment by prudhvigodithi** [comment]
Having a Dockerized solution will help run the app with multiple ports, with different resource and operation files.

**Comment by prudhvigodithi** [comment]
Did a small POC on this. Until we have a full image release for the `opensearch-project/automation-app` in https://hub.docker.com/u/opensearchproject we can do the following:

### Dockerfile

This file will be part of the repo https://github.com/opensearch-project/automation-app/. This controls the node version and dependencies.

```
FROM node:20.8.0
WORKDIR /usr/app
COPY package*.json ./
RUN npm cache clean --force
COPY . .
```

### Docker Compose Files

- To start the app with multiple `OPERATION_CONFIG`'s and on different ports we can run the following compose files.
- Both the process can be part of the same server with different port and the app can listen to multiple operations.
- We can have the following docker compose files added and run part of the user-data, we can run `docker-compose -f compose-1.yaml up -d` and `docker-compose -f compose-2.yaml up -d`.
- We can even explore the auto generation of the compose file or maintain one skeleton and update with `docker-compose` cli.

```
services:
  web-1:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm start
    environment:
      - RESOURCE_CONFIG=configs/resources/sample-resource.yml
      - OPERATION_CONFIG=configs/operations/github-workflow-runs-monitor.yml
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:3000"
``` 
```
services:
  web-2:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm start
    environment:
      - RESOURCE_CONFIG=configs/resources/sample-resource.yml
      - OPERATION_CONFIG=configs/operations/github-merged-pulls-monitor.yml
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:3000"
``` 

Thank you 
@getsaurabh02 @dblock @peterzhuamazon
